new script command now opens script in editor instead of code

diff --git a/new_script b/new_script
--- a/new_script
+++ b/new_script
@@ -18,51 +18,56 @@ ARGUMENTS
 "
 
 while test $# -gt 0; do
-	  case "$1" in
-        -h|--help|-\?)
-            echo "$usage" >&2
-            exit;;
-        -n|--name)
-            name=$2
-            shift;;
-        -p|--path)
-            if [[ "${2}" == "." ]]; then
-                path=$PWD
-            else
-                path=$2
-            fi
-            shift;;
-        \?)
-            echo "Invalid option: -$OPTARG" >&2
-            exit 1;;
-        *)
-            break
-    esac
-    shift
+	case "$1" in
+	-h | --help | -\?)
+		echo "$usage" >&2
+		exit
+		;;
+	-n | --name)
+		name=$2
+		shift
+		;;
+	-p | --path)
+		if [[ "${2}" == "." ]]; then
+			path=$PWD
+		else
+			path=$2
+		fi
+		shift
+		;;
+	\?)
+		echo "Invalid option: -$OPTARG" >&2
+		exit 1
+		;;
+	*)
+		break
+		;;
+	esac
+	shift
 done
 
 if [[ -z "${name}" ]]; then
-    echo "${usage}"
-    exit 1
+	echo "${usage}"
+	exit 1
 fi
 
 if [[ -z "${path}" ]]; then
-    path=$HOME/code/scripts
+	path=$HOME/code/scripts
 fi
 
 full=${path}/$name
 if [[ -f "${full}" ]]; then
-    echo "Error: ${name} already exists in ${path}"
-    echo "Edit $name? y/n"
-    read answer
-    if [[ "${answer}" != "n" ]]; then
-        nvim "${full}"
-    fi
-    exit 0
+	echo "Error: ${name} already exists in ${path}"
+	echo "Edit $name? y/n"
+	read answer
+	if [[ "${answer}" != "n" ]]; then
+		$EDITOR "${full}"
+	fi
+	exit 0
 fi
 
-echo "#!/usr/bin/env bash" > "${full}"
+echo "#!/usr/bin/env bash" >"${full}"
 
 chmod +x "${full}"
 
-nvim "${full}"
+$EDITOR "${full}"
